### ISSUE TITLE
后台给的 url 是在变化的.希望有其他设置标识的办法.

### ISSUE THREAD

**Issue by RaisonWong** [agelessman/MCDownloader#11]
如题

**Comment by agelessman** [comment]
@RaisonWong 这个是不是说，需要把多个url映射成同一个标识，现在有一个问题，你怎么知道这么多url是不是同一个资源？

**Comment by RaisonWong** [comment]
是哦.  那我还是从后台那边去解决好了.

**Comment by agelessman** [comment]
@RaisonWong 大多数是不变化的，我再下个版本中加一个标识符的映射功能把
