### ISSUE TITLE
下载完成之后没有保存 receipt 吗

### ISSUE THREAD

**Issue by liangxueliang** [agelessman/MCDownloader#12]
我用的真机，我发现，在下载完成之后，重新运行，再次点击已经下载的文件，同一个url 取得的receipt 的状态还是 none 而不是 complete，还是会要重新去下载，感觉是下载完成之后没有去保存对应的 receipt 到本地

**Comment by agelessman** [comment]
@liangxueliang 是这样的，当app退到后台或者被系统杀死的时候，才会保存，你要是点击xcode上边的停止，无法监听这个时间，你双击home退出app试试

**Comment by liangxueliang** [comment]
好的，明白了，谢谢
