### ISSUE TITLE
Documents Directory

### ISSUE THREAD

**Issue by serjooo** [agelessman/MCDownloader#14]
Hello,

First of all great utility developed here! Very handy!

I found a bug, where if you are downloading something, stop the download, close the application, open the application again, start the download back, at many times the download returns that the request timed out, then after a few times it is able to download the file, however, what has happened is that the receipt has cached the wrong document's directory path. So the receipt.filePath has the wrong path. I think the filePath has to be always generated again since Documents directory path is not fixed it changes from time to time. Also I think this problem is also causing something else but not sure, when I resume the download I get an expected size, and speed, however, the received size always is 0

**Comment by serjooo** [comment]
I'm not sure if this is the right way to fix it, but seems to be working:

```
- (NSString *)filePath {
    if (_filePath == nil) {
        NSString *path = [cacheFolder() stringByAppendingPathComponent:self.filename];
        if (![path isEqualToString:_filePath] ) {
            if (_filePath && ![[NSFileManager defaultManager] fileExistsAtPath:_filePath]) {
                NSString *dir = [_filePath stringByDeletingLastPathComponent];
                [[NSFileManager defaultManager] createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];
            }
            _filePath = path;
        }
    }
        //Get Current Cache Folder Path with new documents directory path and append the last path component
	return [NSString stringWithFormat:@"%@/%@", cacheFolder(), _filePath.lastPathComponent];
//    return _filePath;
}
```

**Comment by agelessman** [comment]
@serjooo Thank you for your test.
The `filePath` property calls are very frequent, so the code above will have performance problems.
The function of path redirection is increased by `customFilePathBlock`,because many people want to download the file to a custom folder.
The receipt object will be cached to the hard disk in the following four cases：

```objc
applicationWillTerminate
applicationDidReceiveMemoryWarning
applicationWillResignActive
applicationDidBecomeActive
```
So you can not use the stop button on xcode. Do you find the problem in the real machine debugging?
looking forward to your reply.

**Comment by serjooo** [comment]
I see. The way I'm using the APIs is I don't use customFilePathBlock, what I do is I let the downloader download in its on directory and cache and invalidate the downloads to make sure the same download is not downloading at the same instance. Then when the download is complete I move the file to whichever folder I see appropriate because I have different use cases and different folders to handle according to the type of download file. Also, this way I could use my own algorithm to handle duplicate files being saved at the same path and if the user wanted to download the same thing again, the download isn't available in the cache any longer, so it will start the download normally.

As concerning the problem. You do have a point when I don't run build, or stop from xcode, the receipt filePath works correctly. However, still caching absolute paths is wrong, because if this was a real world application, and if you run an update on the store, after the update finishes, the absolute path will change for the documents directory causing the same problem as mentioned above. 

https://stackoverflow.com/questions/9608971/app-updates-nsurl-and-documents-directory

As this post suggests. Using relative paths is always better instead of absolute paths.

**Comment by agelessman** [comment]
@serjooo Thank you very much.
I've added the fix code .
