### ISSUE TITLE
for循环将多个下载任务加到下载列表后多次点击开始暂停会出现无效的情况，所有开始，所有暂停可用

### ISSUE THREAD

**Issue by lxlGit** [agelessman/MCDownloader#5]
for循环将多个下载任务加到下载列表后多次点击开始暂停会出现无效的情况，所有开始，所有暂停可用

**Comment by agelessman** [comment]
@lxlGit 如果你一次性开启了多个下载任务的话，这些任务会按照顺序放入下载队列中，比如，当点击了一个正在下载的任务时，他就在这个队列中删除了，那么就会继续下载下一个等待的任务，如果这时候你又点击了开始，内部会把这个任务拼接到队列的最后边，之后等其他的任务下载完成后，轮到他的时候，他才会下载，因此并不是点击开始就能够立即下载的
