### ISSUE TITLE
下载列表监听的进度不准确

### ISSUE THREAD

**Issue by youzg** [agelessman/MCDownloader#7]
在下载过程中重启之后，列表进度异常，有的还没下完，但progress为空？遇到这个问题，求解答，谢谢

**Comment by agelessman** [comment]
你用我的demo 跑到真机上， 会出现这个情况？

**Comment by youzg** [comment]
@agelessman 谢谢，是模拟器直接重新运行监听不到结束事件。有一个小建议，可以获取已下载和其他状态的列表就更好了，谢谢大神
