### ISSUE TITLE
关于dome的一些问题改进

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [agelessman/MCDownloader#8]
发现有几个问题（只是为了使MCDownloader改进的更好）：
第一个问题：
1.把设置为_downloadQueue.maxConcurrentOperationCount = 1;
2.点击五个Cell的start，只能取消当前下载的这个Cell的start为stop，其他的无法取消。
第二个问题：
1.minion_01.mp4的大小为8.7M，但操作几次后（估计和delete有关），有时候它会变成0.1m/0.1m,然后点击start就播放视频（视频为黑屏，因为0.1M的缘故）
第三个问题：
1.和第二个类似，断线重连无法继续下载（估计和delete有关），点击他就播放，因为没下载完的原因，播放到一半就结束了
第四个问题：
1.进度条显示不统一，比如断线重连后，视频并没有下载完，但是下载进度条已经结束了，要点击start开始才行（如果只是展示功能，没考虑这些UI那这个问题可以忽略吧）

**Comment by agelessman** [comment]
@liunianhuaguoyanxi   第一个问题。我在demo的cell中修改了
```objc
MCDownloadReceipt *receipt = [[MCDownloader sharedDownloader] downloadReceiptForURLString:self.url];
    if (receipt.state == MCDownloadStateDownloading || receipt.state == MCDownloadStateWillResume) {
        
        [[MCDownloader sharedDownloader] cancel:receipt completed:^{
            [self.button setTitle:@"Start" forState:UIControlStateNormal];
        }];
    }else if (receipt.state == MCDownloadStateCompleted) {

        if ([self.delegate respondsToSelector:@selector(cell:didClickedBtn:)]) {
            [self.delegate cell:self didClickedBtn:sender];
        }
    }else {
        [self.button setTitle:@"Stop" forState:UIControlStateNormal];
        [self download];
    }
```
当队列中有待下载的任务是，状态是MCDownloadStateWillResume，其他的问题，，你使用的模拟器吗？ 我保存那个下载信息的策略是，当app死掉或者退出时，点击工程的停止键，兼听不到，因此下载信息没能保存。期待你的回复。。
